name: globe
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-33.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animator: ^3.1.0
  bottomreveal: ^2.0.0
  cached_network_image: ^3.2.3
  crop: ^0.5.3
  flare_flutter: ^3.0.2
  flutter_custom_clippers: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  flutter_speed_dial: ^7.0.0
  simple_animations: ^5.0.0+3
  url_launcher: ^6.1.7
  string_scanner: ^1.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.10
  image: ^3.3.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.0
  image_picker: ^0.8.4+4
  permission_handler: ^11.0.1
  syncfusion_flutter_pdf: ^20.2.47
  syncfusion_flutter_datepicker: ^20.4.54
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/icon/app-store-logo.jpg"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

